version: '3.7'

services:
  quetre:
    #image: quay.io/pussthecatorg/quetre:latest
    build: .
    container_name: quetre
    hostname: quetre
    restart: always
    ports:
      - "127.0.0.1:3007:3007"
    env_file: .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - "NODE_ENV=production"
      - "PORT=3007"

  quetre-redis:
    container_name: quetre_redis
    image: redis
    # FOR DEBUGGING ONLY
    # ports:
    #   - "6379:6379"
    restart: always
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    networks:
      - quetre

networks:
  quetre:
