version: '3.7'

services:
  quetre:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quetre
    hostname: quetre
    restart: always
    ports:
      - "127.0.0.1:3007:3007"
    env_file: .env
    depends_on:
      - quetre_redis
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - "NODE_ENV=production"
      - "PORT=3007"

  quetre_redis:
    container_name: quetre_redis
    hostname: quetre_redis
    image: redis:latest
    restart: always
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    networks:
      - quetre

networks:
  quetre:
